# This is a basic workflow to help you get started with Actions

name: CI_for_todo_app

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"

  deploy:
   runs-on: ubuntu-latest
   steps:
     - name: Hi!
       run : echo "Hi!"
     
     - name: Version(shot sha of git commit)
       run : echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
       
     - name: Configure my AWS Credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
         aws-access-key-id    :  ${{ secrets.AWS_ACCESS_KEY }}
         aws-secret-access-key:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region           :  ${{ secrets.AWS_REGION }}
     
     - name: Check aws creadentials
       run : aws sts get-caller-identity
